### ISSUE TITLE
Is ErrorInformation available?

### ISSUE THREAD

**Issue by dennisl68-castra** [PKISolutions/SSLVerifier.WPF#10]
When using the dll from PoSH and the validation, fails; Where can I find the error information.
I.e. what part failed?

````
PS C:\> Add-Type -Path "C:\Program Files\PKI Solutions\SSL Verifier\SSLVerifier.Core.dll"
PS C:\> $server = New-Object SSLVerifier.Core.Default.ServerEntry "revoked.badssl.com"
PS C:\> $config = New-Object SSLVerifier.Core.Default.CertProcessorConfig
PS C:\> $scanner = New-Object SSLVerifier.Core.Processor.CertProcessor $config
PS C:\> $scanner.StartScan($server)
PS C:\> $server

ServerAddress : https://revoked.badssl.com/
Port          : 443
Proxy         : SSLVerifier.Core.Default.ServerEntryProxy
ItemStatus    : Failed
Log           : SSLVerifier.Core.Default.ServerLogWriter
SAN           : {}
ChainStatus   : CertificateNotFound
Certificate   :
Tree          : {}
````

````
PS C:\> Add-Type -Path "C:\Program Files\PKI Solutions\SSL Verifier\SSLVerifier.Core.dll"
PS C:\> $server = New-Object SSLVerifier.Core.Default.ServerEntry "expired.badssl.com"
PS C:\> $config = New-Object SSLVerifier.Core.Default.CertProcessorConfig
PS C:\> $scanner = New-Object SSLVerifier.Core.Processor.CertProcessor $config
PS C:\> $scanner.StartScan($server)
PS C:\> $server

ServerAddress : https://expired.badssl.com/
Port          : 443
Proxy         : SSLVerifier.Core.Default.ServerEntryProxy
ItemStatus    : Failed
Log           : SSLVerifier.Core.Default.ServerLogWriter
SAN           : {}
ChainStatus   : CertificateNotFound
Certificate   :
Tree          : {}
````

**Comment by Crypt32** [comment]
In your given case, error is `CertificateNotFound`, this means that TLS handshake failed and we didn't get any certificate to validate. I can suspect that the issue is due to TLS version or cipher mismatch. It does work for me:

```
PS C:\Users\Administrator.CONTOSO> $server.Log.text
PS C:\Users\Administrator.CONTOSO> cd\
PS C:\> Add-Type -Path "C:\Program Files\PKI Solutions\SSL Verifier\SSLVerifier.Core.dll"
PS C:\> $server = New-Object SSLVerifier.Core.Default.ServerEntry "revoked.badssl.com"
PS C:\> $config = New-Object SSLVerifier.Core.Default.CertProcessorConfig
PS C:\> $scanner = New-Object SSLVerifier.Core.Processor.CertProcessor $config
PS C:\> $scanner.StartScan($server)
PS C:\> $server


ServerAddress : revoked.badssl.com
Port          : 443
Proxy         : SSLVerifier.Core.Default.ServerEntryProxy
ItemStatus    : Failed
Log           : SSLVerifier.Core.Default.ServerLogWriter
SAN           : {DNS Name=revoked.badssl.com, DNS Name=www.revoked.badssl.com}
ChainStatus   : NoError
Certificate   : [Subject]
                  CN=revoked.badssl.com, O=Lucas Garron Torres, L=Walnut Creek, S=California, C=US

                [Issuer]
                  CN=DigiCert SHA2 Secure Server CA, O=DigiCert Inc, C=US

                [Serial Number]
                  0371B58A86F6CE9C3ECB7BF42F9208FC

                [Not Before]
                  2019.10.04. 03:00:00

                [Not After]
                  2021.10.08. 15:00:00

                [Thumbprint]
                  23FC13BA6F27BF8DD1761BDA7BB41921F59C21F7

Tree          : {SSLVerifier.Core.Models.TreeNode`1[SSLVerifier.Core.IChainElement]}



PS C:\>
```

**Comment by dennisl68-castra** [comment]
I recon the upstream proxy server intervened on “my behalf”. 
I’ll check with another internet connection tomorrow.

**Comment by dennisl68-castra** [comment]
Yes, the upstream proxy did some magic.

But I still can't tell *why* the verification failed...

In PSPKI, the Test-WebServerSSL had a property called ErrorInformation that was very useful.
Can I find this the corresponding information using PoSH and SSLVerifier.Core.dll?

**Comment by Crypt32** [comment]
`ErrorInformation` returns exactly the same information as `ChainStatus` in SSLVerifier.Core.dll.

**Comment by dennisl68-castra** [comment]
Well, not quite.
In an isolated environment with no internet access.
Test-WebServerSSL, ErrorInformation will be
``ErrorInformation:    {RevocationStatusUnknown, OfflineRevocation}``
while using SSLVerifier.Core.dll, ChainStatus will be
``ChainStatus:    CertificateNotFound``

I can understand what went wrong with Test-WebServerSSL, I haven't a clue why the DLL is telling me that :/
(Unless, of course I already know the internet connection is broken.)
The DLL ChainStatus is even misleading, since the certificate was actually read (or should have been as that is possible).

**Comment by Crypt32** [comment]
I will check this when get spare time.

**Comment by Crypt32** [comment]
Ok,I changed the tool a bit. It seems that `ChainStatus` property was never updated. Now it does aggregate all chain issues from all chains for specified endpoint. In addition, `$server.Log.Text` now stores text log you see in GUI version. Wouldn't you mind to download newest version (must be 1.5.6) and try again?

**Comment by dennisl68-castra** [comment]
Sure thing...

**Comment by dennisl68-castra** [comment]
ChainLog now presents me with much more reasonable messages in 1.5.6 :)

'expired' will produce
``ChainStatus:    NotTimeValid``

'revoked' will produce
``ChainStatus:    Revoked``

'no internet access' will produce
``ChainStatus:    RevocationStatusUnknown, OfflineRevocation, CertificateNotFound``

I will have a look at Log.Text as well...

**Comment by dennisl68-castra** [comment]
Yes. The $server.Log.Text now also contains very useful information :)

But with no internet access, the last error message doesn't match.
'CertificateNotFound' in ``ChainStatus`` is 'Server requested authorization (HTTP/401), cannot proceed.' in ``$server.Log.Text``
I assume that this is the upstream proxy requesting a login in my isolated site.

**Comment by Crypt32** [comment]
> But with no internet access, the last error message doesn't match.

this exception is from SChannel. I don't have control over it.

> I assume that this is the upstream proxy requesting a login in my isolated site.

either, a proxy or endpoint itself.

**Comment by dennisl68-castra** [comment]
> this exception is from SChannel. I don't have control over it.

Ok, then it works by design :)

**Comment by Crypt32** [comment]
If you are ok with this fix, you can close this issue.

**Comment by dennisl68-castra** [comment]
Sweet :)
