### ISSUE TITLE
Issue saving server list

### ISSUE THREAD

**Issue by lukiwski** [PKISolutions/SSLVerifier.WPF#7]
Issue when saving server list as follows:

There was an error reflecting type 'SSLVerifier.API.ModelObjects.XmlObject'.

**Comment by matlup00** [comment]
Just tried that tool and it helped me find what was the problem with my certificate. Thank you !

Got exactly the same problem as lukiwski when saving server list:

There was an error reflecting type 'SSLVerifier.API.ModelObjects.XmlObject'.

Any Hint ?

**Comment by Crypt32** [comment]
It is a known issue. I doubt it ever worked. I'll get this fixed in next version when I get a time for this project.

**Comment by matlup00** [comment]
Thank you Crypt32, 
Is there a ServerList.xml sample template available ? 
Is the "File/Open server list" feature works ?
I would like to build my own xml file manually to check all my SSL certificates.

Thank you.

**Comment by kruxarn** [comment]
Please fix this problem, please please :)

**Comment by rajahbean** [comment]
Issue is in the ServerObject.cs in which the IServerProxy Proxy interface wasn't marked as XmlIgnore.  Once corrected, the save and load processes work as expected.

Thank you for this tool, very helpful when dealing with multiple certificates and endpoints.

**Comment by Crypt32** [comment]
When I get time, I will fix this. I'm planning to replace XML format with JSON.

**Comment by Crypt32** [comment]
The fix above includes proxy configuration as well, except for password. Proxy password isn't exported for privacy reasons.

**Comment by rajahbean** [comment]
Hi Crypt32, Great news.   We are actively using as a way for a Level 1 support to validate during certificate updates.   We needed to be able to save and load lists so I thought I would fix.

After fix, I did notice that I bypassed the Proxy settings so I realized someone may need that, we didn't.

Thank You

**Comment by MegaTruckMike** [comment]
Crypt32.  

Thanks a bunch for fixing the sslvalidator tool   Any chance you can post a new compiled version of it with your changes?

thanks a bunch.

**Comment by Crypt32** [comment]
MSI installer is uploaded: https://www.pkisolutions.com/tools/sslcertverifier/

**Comment by MegaTruckMike** [comment]
Thank you can not wait to try it.
